config/routes.rb
Rails.application.routes.draw do
  get 'creatives/index'

  get 'users/show'
  devise_for :users
  resources :users, only: [:show]

  resources :users, only: [] do
      resources :categories, only: [:show]

  end
  resources :categories do
    resources :options, except: [:index]
  end

  resources :categories, only: [] do
    resources :favorites, only: [:index, :create, :destroy]
  end

  resources :options, only: [] do
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  get 'about' => 'welcome#about'
  root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :options, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :category

  has_many :votes, dependent: :destroy

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def favorite_for(category)
    favorites.where(category_id: category.id).first
  end


end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :option

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception

  #before_action :authenticate_user!

  # commenting for default creating
  # there does not need to be a user yet but functionality works
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @option = Option.find(params[:id])

  end

  def new
    @category = Category.new
  end

  def create
    # @category = Category.new
    # @category.title = params[:category][:title]
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      flash[:notice] = "Category saved."
      redirect_to @category
    else
      flash.now[:alert] = "There was an error creating your Category."
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    # @category.title = params[:category][:title]
    @category.assign_attributes(category_params)

    if @category.save
      flash[:notice] = "Category updated."
      redirect_to @category
    else
      flash.now[:alert] = "There was an error saving the category."
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])

    if @category.destroy
      flash[:notice] = "\"#{@category.title}\" was deleteed successfully"
      redirect_to categories_path
    else
      flash.now[:alert] = "There was an error deleting the category"
      render :show
    end
  end

  private
  def category_params
    params.require(:category).permit(:title, :public)
  end
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"

  def index
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorite = current_user.favorites.all
  end

  def create
    category = Category.find(params[:category_id])
    favorite = current_user.favorites.build(category: category)

    if favorite.save
      flash[:notice] = "Category favorited."
    else
      flash[:alert] = "Favoriting failed."
    end
      redirect_to category
  end

  def destroy
    category = Category.find(params[:category_id])
    favorite = current_user.favorites.find(params[:id])

    if favorite.destroy
      flash[:notice] = "Category unfavorited."
    else
      flash[:alert] = "Failed"
    end

    redirect_to category
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController

  def show
    @option = Option.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @option = Option.new
  end




  def create
  #  @option = Option.new
  #  @option.title = params[:option][:title]
  #  @option.body = params[:option][:body]
  #  @option.website = params[:option][:website]
    @category = Category.find(params[:category_id])
    @option = @category.options.build(option_params)
    #@option.user = current_user

    #@option.category = @category

    if @option.save
      flash[:notice] = "Option added."
      redirect_to [@category, @option]
    else
      flash.now[:alert] = "Error creating option"
      render :new
    end
  end

  def edit
    @option = Option.find(params[:id])
  end

  def update
    @option = Option.find(params[:id])
    # @option.title = params[:option][:title]
    # @option.body = params[:option][:body]
    # #@option.website = params[:option][:website]
    @option.assign_attributes(option_params)

    if @option.save
      flash[:notice] = "Option was updated."
      redirect_to [@option.category, @option]
    else
      flash.now[:alert] = "There was an error updating this otption"
      render :edit
    end
  end

  def destroy
    @option = Option.find(params[:id])

    if @option.destroy
      flash[:notice] = "\"#{@option.title}\" was deleted."
      redirect_to @option.category
    else
      flash.now[:alert] = "There was an error deleting option"
      render :show
    end
  end


  private
  def option_params
    params.require(:option).permit(:title, :body, :website)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    @email = @user.email
    @favorite = @user.favorites
  end

  def user_profile
    redirect_to current_user
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def up_vote
    update_vote(1)
    redirect_back(fallback_location: :root)
  end

  def down_vote
    update_vote(-1)
    redirect_back(fallback_location: :root)
  end

  private
  def update_vote(new_value)
    @option = Option.find(params[:option_id])
    @vote = @option.votes.where(user_id: current_user.id).first

    if @vote
      @vote.update_attribute(:value, new_value)
    else
      @vote = current_user.votes.create(value: new_value, option: @option)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/options_helper.rb
module OptionsHelper

  def random_option(category)
    category.options.pluck(:id).sample

  end

  def actual_option(category)
    category.options.pluck(:id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/edit.html.erb
<h1> Edit Category </h1>

<div class="row">
  <div class="col-4-md">
    <p> Edit this Category </p>
  </div>
  <div class="col-md-8">
    <%= form_for @category do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter category title" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<h3>Categories<%= link_to "New Category", new_category_path(@category), class: 'btn btn-success' %></h3>



<div class="col-lg-4 col-sm-6">
  <ul>
    <% @categories.each do |category| %>
    <div class= "media">
      <div class="media-body">
        <h4 class="media-heading">
          <li><%= link_to category.title, category %>
          <small> submitted <%= time_ago_in_words(category.created_at) %> ago by <%= category.user.email %> <br> </small></li>
        </h4>
      </div>
    </div>
  <% end %>
  </ul>
</div>

app/views/categories/new.html.erb
<h1> Make a Category </h1>


<div class="row">
  <div class="col-md-4">
    <p> Create a custom Category </p>
  </div>
  <div class="col-md-8">
    <%= form_for @category do |f| %>
      <div class="form-group"?
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class="form-group">
        <%= f.submit "Save" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
 <h1>
  <%= @category.title %>
  <%= link_to "Add Option", new_category_option_path(@category), class: 'btn btn-success' %>
  <%= link_to "Edit", edit_category_path(@category), class: 'btn btn-success' %>
  <%= link_to "Delete Category", @category, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this category_instance?'} %>
  <% if @category.options.any? %>
     <%= link_to "Choose 4 ME!", category_option_path(@category, random_option(@category)), class: 'btn btn-success'%>
   <% else %>
     <p> Add some options! </p>
   <% end %>

  </h1>

 <div class="col-md-4 pull-right">


 </div>

 <div class="row">
   <div class="col-md-8">
     <%= render partial: 'favorites/favorite', locals: { category: @category } %>
     <% @category.options.each do |option| %>
      <div class="media">

         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to option.title, category_option_path(@category, option.id) %>
           </h4>
         </div>
      </div>
    <% end %>
   </div>
 </div>

app/views/creatives/_bg_primary.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">We've got what you need!</h2>
                <hr class="light">
                <p class="text-faded">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
                <a href="#" class="btn btn-default btn-xl">Get Started!</a>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_call_to_action.html.erb
<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Free Download at Start Bootstrap!</h2>
            <a href="#" class="btn btn-default btn-xl wow tada">Download Now!</a>
        </div>
    </div>
</aside>

app/views/creatives/_contact.html.erb
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Let's Get In Touch!</h2>
                <hr class="primary">
                <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-phone fa-3x wow bounceIn"></i>
                <p>123-456-6789</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                <p><a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a></p>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_header.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner" >

        </div>
    </div>
</header>

app/views/creatives/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">Start Bootstrap</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="#about">About</a>
                </li>
                <li>
                    <a class="page-scroll" href="#services">Services</a>
                </li>
                <li>
                    <a class="page-scroll" href="#portfolio">Portfolio</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/creatives/_portfolio.html.erb
<section class="no-padding" id="portfolio">
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/1.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/2.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/3.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/4.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/5.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/6.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_services.html.erb
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">At Your Service</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-diamond wow bounceIn text-primary"></i>
                    <h3>Pick a Category</h3>
                    <p class="text-muted">With so many options to choose from let us pick for you.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
                    <h3>Reviews available!</h3>
                    <p class="text-muted">When we give you an option, there is a ton of reviews and information at your finger tips!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                    <h3>Up to Date</h3>
                    <p class="text-muted">Always adding new and exciting options in your area!</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                    <h3>Made with Love</h3>
                    <p class="text-muted">Don't you hate when the group can't decide on a place to eat? An activity to do? Wait no further! We got you!</p>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/creatives/index.html.erb
<%= render 'creatives/navbar' %>
<%= render 'creatives/header' %>
<%= render 'creatives/bg_primary' %>
<%= render 'creatives/services' %>
<%= render 'creatives/portfolio' %>
<%= render 'creatives/call_to_action' %>
<%= render 'creatives/contact' %>

app/views/favorites/_favorite.html.erb
  <% if favorite = current_user.favorite_for(@category) %>
    <%= link_to [@category, favorite], class: 'btn btn-danger', method: :delete do %>
    <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unfavorite
  <% end %>
<% else %>
  <%= link_to [@category, Favorite.new], class: 'btn btn-primary', method: :category do %>
    <i class="glyphicon glyphicon-star"> </i>&nbsp; Favorite
  <% end %>
<% end %>

app/views/favorites/_list.html.erb
<h2>Favorites</h2>

<div class="col-md-4">
  <% current_user.favorites.each do |favorite| %>
  <ul>
    <%= link_to Category.find_by_id(favorite.category_id).title, user_category_path(@user, favorite.category_id) %>
  </ul>
  <% end %>
</div>

app/views/options/edit.html.erb
<h1> Edit Option</h1>

<div class="row">
  <div class="col-4-md">
    <p> Edit this Option </p>
  </div>
  <div class="col-md-8">
    <%= form_for [@option.category, @option] do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter option title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter option discription" %>
      </div>
      <div class="form-group">
        <%= f.label :website %>
        <%= f.text_field :website, class: 'form-control', placeholder: "Enter URL" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/options/new.html.erb
<h1> Add an Option! </h1>


<div class="row">
  <div class="col-md-4">
    <p> Create a custom Option </p>
  </div>
  <div class="col-md-8">
    <%= form_for [@category, @option] do |f| %>
      <div class="form-group"?
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Option name" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter option discription" %>
      </div>
      <div class="form-group">
        <%= f.label :website %>
        <%= f.text_field :website, class: 'form-control', placeholder: "Enter URL" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save" %>
      </div>
    <% end %>
  </div>
</div>

app/views/options/show.html.erb
            <div>
              <h1><%= @option.title %></h1> <br>
              <div class="vote-arrow pull-left">
                <%= render partial: 'votes/voting', locals: { option: @option } %>
              </div>
            </div>

            <div class="col-md-4">
              <%= link_to "Choose 4 ME!", category_option_path(@option.category_id, random_option(@option.category)), class: 'btn btn-success'%>
              <%= link_to "Edit", edit_category_option_path(@option.category, @option), class: 'btn btn-success' %>
              <%= link_to "Delete Option", [@option.category, @option], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this option?' } %>
              <h3>
                <%= pluralize(@option.points, 'point') %>
              <div>
                <small>
                  <%= pluralize(@option.up_votes, 'up vote') %>,
                  <%= pluralize(@option.down_votes, 'down vote') %>
                </small>
                </div>
              </h3>
            </div>

          


            <div class= "row">
                <div class="cold-md-8 ">
                  <ul>
                      <li><%= @option.body %></li>
                      <li><%= @option.website %></li>
                  </ul>
                </div>
            </div>

app/views/users/show.html.erb
  <h1><%= @user.email %>'s Favorites</h1>

  <div class="row">
    <div class="col-md-8">
      <%= render partial: 'favorites/list', locals: { category: @category } %>
    </div>
  </div>

app/views/votes/_voting.html.erb
 <div class="vote-arrows pull-left">
  <div><%= link_to " ", option_up_vote_path(option), class: 'glyphicon glyphicon-chevron-up', method: :post %></div>
   <div><strong><%= option.points %></strong></div>
  <div><%= link_to " ", option_down_vote_path(option), class: 'glyphicon glyphicon-chevron-down', method: :post %></div>

 </div>

app/views/welcome/about.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">We have mastered the art of indecisiveness.</h2>
                <hr class="light">
                <p class="text-faded">Let us choose 4 you!</p>
                  <p class="text-faded">
                    Picking something when there are so many options in the world is hard!
                    Sometimes you waste time! When you pick a category you can select a
                    specfic option from it or have us choose 4 you!
                  </p>
            </div>
        </div>
    </div>
</section>
<%= render 'creatives/services' %>

app/views/welcome/index.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">We've got what you need!</h2>
                <hr class="light">
                <p class="text-faded">Let us choose 4 you!</p>
                  <%= link_to "Get Started", new_user_registration_path, class: "btn btn-default btn-xl" %>

            </div>
        </div>
    </div>

</section>

  <%= render 'creatives/services' %>
  