config/routes.rb
Rails.application.routes.draw do
  get 'creatives/index'

  get 'users/show'
  devise_for :users
  resources :users, only: [:show]

  resources :users, only: [] do
      resources :categories, only: [:show]

  end
  resources :categories do
    resources :options, except: [:index]
  end

  resources :categories, only: [] do
    resources :favorites, only: [:index, :create, :destroy]
  end

  resources :options, only: [] do
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  get 'about' => 'welcome#about'
  root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :options, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :category

  has_many :votes, dependent: :destroy

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def favorite_for(category)
    favorites.where(category_id: category.id).first
  end


end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :option

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @option = Option.find(params[:id])

  end

  def new
    @category = Category.new
  end

  def create
    # @category = Category.new
    # @category.title = params[:category][:title]
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      flash[:notice] = "Category saved."
      redirect_to @category
    else
      flash.now[:alert] = "There was an error creating your Category."
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    # @category.title = params[:category][:title]
    @category.assign_attributes(category_params)

    if @category.save
      flash[:notice] = "Category updated."
      redirect_to @category
    else
      flash.now[:alert] = "There was an error saving the category."
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])

    if @category.destroy
      flash[:notice] = "\"#{@category.title}\" was deleteed successfully"
      redirect_to categories_path
    else
      flash.now[:alert] = "There was an error deleting the category"
      render :show
    end
  end

  private
  def category_params
    params.require(:category).permit(:title, :public)
  end
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"

  def index
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorite = current_user.favorites.all
  end

  def create
    category = Category.find(params[:category_id])
    favorite = current_user.favorites.build(category: category)

    if favorite.save
      flash[:notice] = "Category favorited."
    else
      flash[:alert] = "Favoriting failed."
    end
      redirect_to category
  end

  def destroy
    category = Category.find(params[:category_id])
    favorite = current_user.favorites.find(params[:id])

    if favorite.destroy
      flash[:notice] = "Category unfavorited."
    else
      flash[:alert] = "Failed"
    end

    redirect_to category
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController

  def show
    @option = Option.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @option = Option.new
  end




  def create
  #  @option = Option.new
  #  @option.title = params[:option][:title]
  #  @option.body = params[:option][:body]
  #  @option.website = params[:option][:website]
    @category = Category.find(params[:category_id])
    @option = @category.options.build(option_params)
    #@option.user = current_user

    #@option.category = @category

    if @option.save
      flash[:notice] = "Option added."
      redirect_to [@category, @option]
    else
      flash.now[:alert] = "Error creating option"
      render :new
    end
  end

  def edit
    @option = Option.find(params[:id])
  end

  def update
    @option = Option.find(params[:id])
    # @option.title = params[:option][:title]
    # @option.body = params[:option][:body]
    # #@option.website = params[:option][:website]
    @option.assign_attributes(option_params)

    if @option.save
      flash[:notice] = "Option was updated."
      redirect_to [@option.category, @option]
    else
      flash.now[:alert] = "There was an error updating this otption"
      render :edit
    end
  end

  def destroy
    @option = Option.find(params[:id])

    if @option.destroy
      flash[:notice] = "\"#{@option.title}\" was deleted."
      redirect_to @option.category
    else
      flash.now[:alert] = "There was an error deleting option"
      render :show
    end
  end


  private
  def option_params
    params.require(:option).permit(:title, :body, :website)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    @email = @user.email
    @favorite = @user.favorites
  end

  def user_profile
    redirect_to current_user
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def up_vote
    update_vote(1)
    redirect_back(fallback_location: :root)
  end

  def down_vote
    update_vote(-1)
    redirect_back(fallback_location: :root)
  end

  private
  def update_vote(new_value)
    @option = Option.find(params[:option_id])
    @vote = @option.votes.where(user_id: current_user.id).first

    if @vote
      @vote.update_attribute(:value, new_value)
    else
      @vote = current_user.votes.create(value: new_value, option: @option)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/options_helper.rb
module OptionsHelper

  def random_option(category)
    category.options.pluck(:id).sample

  end

  def actual_option(category)
    category.options.pluck(:id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<!-- <ul class="nav nav tabs">
  <li><%= link_to "Choose4me", root_path %>
  <li><%= link_to "About", about_path %>
  <li><%= link_to "Categories", categories_path %>
  <div class="pull-right user-nav-links">
    <% if user_signed_in? %>
       <li class = "signed-in">Signed in as: <strong><%= current_user.email %></strong> </li>
       <li><%= link_to 'Proflie', users_show_path %> - <%= link_to 'Edit Account', edit_user_registration_path %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
   <% else %>
       <li><%= link_to "Sign Up", new_user_registration_path  %> -
       <%= link_to "Sign In", new_user_session_path  %></li>
   <% end %>
 </div>
</ul> -->


<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top"><%= link_to "Choose4ME", root_path %></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="#about"><%= link_to "About", about_path %></a>
                </li>
                <li>
                    <a class="page-scroll" href="#portfolio"><li><%= link_to "Categories", categories_path %></a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">
                      <% if user_signed_in? %>
                           Signed in as: <strong><%= current_user.email %></strong>
                           <li><%= link_to 'Proflie', users_show_path %> - <%= link_to 'Edit Account', edit_user_registration_path %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                       <% else %>
                           <li><%= link_to "Sign Up", new_user_registration_path  %> -
                           <%= link_to "Sign In", new_user_session_path  %></li>
                       <% end %></a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Choose4me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'creative/manifest.css', media: 'all' %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag 'creative/manifest.js' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <%= render 'layouts/navbar' %>
  <%= render 'creatives/header' %>


  <body>


    <%= yield %>
  </body>
</html>

app/views/layouts/creative.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Start Bootstrap Creative</title>
  <%= stylesheet_link_tag 'creative/manifest.css', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'creative/manifest.js' %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

</body>
</html>